coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "setup.py"
  - "docs/**/*"
  - "examples/**/*"
  - "scripts/**/*"
